name: Lint

on:
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Run lint
        run: pnpm run lint
